name: Download and Push Image
on:
  schedule:
    - cron: '1 23 * * *'
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      # with:
      #   python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: run bingjson
      run: python ./python/bing_all_langs_fullstartdate.py

    - name: Commit and Push
      run: |
        git status
        git diff
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add downloaded image"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
